name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  build:
    name: build & push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: danieltrick/rust-tss2-docker

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release:
    name: GitHub release
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Pull and save the Docker image
        run: |
          docker image pull --platform linux/${{ matrix.platform }} danieltrick/rust-tss2-docker:${{ github.ref_name }}
          docker image save danieltrick/rust-tss2-docker:${{ github.ref_name }} | xz -9v > rust_tss2_docker-${{ github.ref_name }}.linux-${{ matrix.platform }}.tar.xz

      - name: Upload image to GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: rust_tss2_docker-${{ github.ref_name }}.linux-${{ matrix.platform }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
